---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lession-05-pvc
  namespace: homework
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: lession-05-storage 
